print('==========CONVITE DE FESTA==========')
nome=str(input('Digite seu nome: '))
nome=nome.upper()
print('Olá, %s. Você foi convidado para a festa.'%nome)
print('====================================')
